### ISSUE TITLE
Review speed issues

### ISSUE THREAD

**Issue by johnnonweiler** [ScottishCovidResponse/SCRCIssueTracking#102]
Consider running a profiler, and check if there are any simple ways that the code can be made significantly faster (e.g. by replacing a list with a dictionary).

**Comment by johnnonweiler** [comment]
After my comment earlier about possibly speeding up the use of ‘PoissonDistribution’, I had a quick look at reusing objects, instead of recreating the ‘PoissonDistribution’ objects for every new sample.  It seemed like it was probably a bit faster, but didn’t make a big difference.

https://github.com/ScottishCovidResponse/Covid_Simulation_Model/pull/17

**Comment by johnnonweiler** [comment]
@BlairArchibald Please could you update this issue when you've reviewed the current status?

**Comment by BlairArchibald** [comment]
Speed issues were looked at in https://github.com/ScottishCovidResponse/Covid_Simulation_Model/pull/78

The biggest issue was the sheer number of RNG calls required to handle neighbor movement. These have been reduced by sampling visits daily instead of hourly.

Given the number of calls to each function (e.g. to move every person), even small improvements can have significantly effects. As such this is an ongoing issue.

**Comment by johnnonweiler** [comment]
This is an ongoing issue, that I'm sure we'll want to come back to, but let's avoid having GitHub issues that we keep permanently open.  I'll close this for now, and then make a new ticket when we next have something specific (or bounded) that we want to do related to this.
