### ISSUE TITLE
Develop Testing Plan

### ISSUE THREAD

**Issue by bobturneruk** [ScottishCovidResponse/SCRCIssueTracking#106]
Come up with a plan for implementing testing for this repository and obtain agreement from team. On the basis of this raise additional GitHub issues as needed to get the plan going.

**Comment by aflag** [comment]
I'm working on this

**Comment by aflag** [comment]
I have done some reading and @magicicada has helped me understanding the code and giving ideas on how to test it.

My suggestion is that we start off by creating a simple **regression test** on basicSimulation. For this, I suggest we pass in the random generator (`random.Random`) as a parameter of basicSimulation. Alternatively, we could make basicSimulation competely deterministic by receiving a list of first infected people as a parameter (maybe this is not realistic as the function may have other sources of randomness in future). I believe this test is sort of an easy win for us to be able to refactor and move bits of the code around without risking breaking it.

After that one is done, we can move forwards with more **unit testing**. For that, we could start by testing simple tests for the the data loading functions. We can change them slightly so that we pass a file object instead of the file name, so that we can easily create fixtures.  Given that we expect changes in the input format soon, I believe it's nice to have tests on these. We can also make simple unit tests for stages of the model: doInternalProgressionAllNodes, doInteralInfectionProcessAllNodes, doBetweenInfectionAgeStructured. Given they are currently pure functions, that would give us confidence that the steps behave as we want. Here, I think it could be useful to split the functions into modules, so that we can assess the coverage individually and easily break into testing tasks.

Now, tackling the broader concept if the model is correct and converging. I couldn't find any popular projects and practices other than the regression test I described previously. However, I could find an article from some people who were testing something very similar to us (https://homes.cs.washington.edu/~borning/papers/sevcikova-issta-2006.pdf). It's a bit of an old article (and I couldn't find many citations to it, except for this one: https://dl.acm.org/doi/pdf/10.1145/1295074.1295084). However, I think they raise a few good arguments. A regression test with a fixed seed can be a bit brittle (just changing the order when the random() calls are made can break it).  Their solution was to look at the output distribution and check if it matches the expected distribution. Given that we currently don't have that much non-determinism, I'm not sure we need to implement anything like that right now, but I think we should at least keep that in mind. However, one of the ideas from the machine learning people (https://developers.google.com/machine-learning/testing-debugging/pipeline/deploying), is that we can try to validate that our model converges, It would be nice if we could try to come up with sets of inputs that should be equivalent and see if they all generate a similar output.

For the technicalities, I suggest we use pytest, imho it's quite a bit better than the default unittests from python. I think using the coverage package is also a good idea here.

**Comment by bobturneruk** [comment]
Great work @aflag! I'm happy with this - I suggest that we follow this guidance and @aflag raises an issues on regression testing and unit testing and gets going on regression testing initially. Bringing in some zulip chat, I think we also need an issue on virtual environment, this should be anaconda based. I'll raise this if no one else gets there first!

@aflag any thoughts on how this might work with CI? I've used GitHub actions (which is very new) a bit and I think it should be possible to get the regression and unit tests running automatically on GitHub triggered by PRs.

I suggest we leave this issue open for further discussion on model correctness and convergence (thanks for the links on this). This is a tricky topic and I'm sure we'll get perspectives from those elsewhere in SCRC.

**Comment by aflag** [comment]
In terms of CI, the tool I have most experience with is jenkins, but I don't think it's a good fit here. I have worked with circle ci in the past and I like it, but I'm open to try github actions. I like the idea of minimising external dependencies.

**Comment by bobturneruk** [comment]
Not used circle, agree on jenkins. I think you'll like GH actions!
