### ISSUE TITLE
Scan code for any hardcoded parameters

### ISSUE THREAD

**Issue by magicicada** [ScottishCovidResponse/SCRCIssueTracking#165]
Check through the main model for any parameters that are still hard-coded (we used this during very early develepment for toy model).  Make a list of these, and then we can raise issues to instead read them from file, provide as params from calling code, etc.

**Comment by aflag** [comment]
One thing related to this. https://github.com/ScottishCovidResponse/simple_network_sim/blob/master/sample_input_files/paramsAgeStructured encodes the progression of the (just missing the S -> E connection). Maybe, one of the tasks for this could be to encode the entire graph in that file. The way I think this relates to removing hardcoded parameters is that we could also encode which nodes are considered "infectious", which ones are "susceptible", etc. So, if we decided to consider hospitalized infectious, for instance, it would just be a matter of changing that file.

**Comment by bobturneruk** [comment]
Where is `S -> E` currently, please?

**Comment by magicicada** [comment]
S->E is driven by the age mixing matrix (which is not yet read from file, though we are working on it), and by the weights of the network edges.

**Comment by aflag** [comment]
# Parameters

These are the parameters we take for our model

- RNG
- Graph (regions/weights)
- Number Infected
- Time Horizon
- Generic Infections (not used)
- Age infection Matrix
- Diseases Progression
- Dict of states

After the changes I here, that will look like this:

- Graph (regions/weights)
- Time Horizon
- Age infection Matrix
- Diseases Progression
- Dict of states (prepoluated with infected people and computed from the disaeses progression, graph + 'S')
- Optiona: State graph labels

https://github.com/ScottishCovidResponse/simple_network_sim/blob/master/simple_network_sim/network_of_populations.py#L89-L91

# Tasks proposal

## 1. Derive age and states from the other parameters in basicSimulationInternalAgeStructure

basicSimulationInternalAgeStructure: https://github.com/ScottishCovidResponse/simple_network_sim/blob/master/simple_network_sim/network_of_populations.py#L89-L91

* numInside can be removed
* age can be extracted from ageInfectionMatrix
* states can be either retrieved from the dictOfStates

We could probably take the opportunity to remove the genericInfection parameter from the same function and doBetweenInfectionAgeStructured as part of this task

## 2. Create a function for the initial infection

Refactor the code from here: https://github.com/ScottishCovidResponse/simple_network_sim/blob/master/simple_network_sim/network_of_populations.py#L94-L98 into its own function that can infect people from any age group or node (this can be read from a file even). basicSimulationInternalAgeStructure can then be called with the dictOfStates already populated as needed.

Hopefully that logic can be shared with setupInitialPopulation, which should also be changed here: https://github.com/ScottishCovidResponse/simple_network_sim/blob/master/simple_network_sim/sampleUseOfModel.py#L47 so that it derives the age and compartments the same way basicSimulationInternalAgeStructure does

## 3. Use the new age transitions loader code

Change https://github.com/ScottishCovidResponse/simple_network_sim/blob/master/simple_network_sim/sampleUseOfModel.py#L22-L32 to use the loaded matrix, instead of the current hard coded one

## 4. Refactor every usage of "<state>" (eg.: 'S', 'A', etc.) into a general function

For this I propose the following changes:

### Init new state

This bit:

```
        nextTime = time+1
        if nextTime not in dictOfStates:
            dictOfStates[nextTime] = {}
            for node in graph.nodes():
                dictOfStates[nextTime][node] = {}
                for age in ages:
                    for state in states:
                        dictOfStates[nextTime][node][(age, state)] = 0
```

But copying the number of susceptibles from the previous state.

### Internal Progression

It can simply iterate over diseaseProgressionProbs and not care about "S" being a special case

### Internal Infection

It should call a function called `infect` which will implement this:

```
                dictOfStates[nextTime][node][(age, 'E')] = dictOfStates[nextTime][node][(age, 'E')] + newInfected[age]
                dictOfStates[nextTime][node][(age, 'S')] = dictOfStates[nextTime][node][(age, 'S')] - newInfected[age]
```

It should use getSusceptible instead of calling this :

```
numSuscept = currentInternalStateDict[(age, 'S')]

```

In this line

```
                totalInfectious = currentInternalStateDict[(ageInf, 'I')] + currentInternalStateDict[(ageInf, 'A')]
```

it can instead call a function called getSpreaders (it'll do what countInfectionsAgeStructured does, but there's a difference between people who are infected and people who are spreaders)

### Between nodes infections

Will also call getSucceptibles (through distributeInfections)

This already calls `getTotalInfected`, but maybe it should call get spreaders

Calls infect rather than

```
           dictOfStates[currentTime+1][vertex][(age, 'S')] = dictOfStates[currentTime+1][vertex][(age, 'S')] - deltaByAge[age]
           dictOfStates[currentTime+1][vertex][(age, 'E')] = dictOfStates[currentTime+1][vertex][(age, 'E')] + deltaByAge[age]
```

## 4. (optional) Parametrise S->E, spreader nodes and infected nodes

Given that all transitions through states are encoded in functions, we could make the behaviour of them parameterised. But maybe, it's simpler to just change the functions at that point.

**Comment by magicicada** [comment]
I'm not totally sure what you mean by (4), but I like the others.  Obviously they'll all need their own issues and plans.  As you might have guessed I'd been thinking about some of them myself, but not gotten around to it - enormously grateful that you have :)

**Comment by aflag** [comment]
The diseases progression graph is already fully described by this: https://github.com/ScottishCovidResponse/simple_network_sim/blob/master/sample_input_files/paramsAgeStructured

With the 4th task I was thinking about a way to create a similar file for describing the infection distribution part. The code right now needs to know which node to connect S to (so that people can get infected). We need to know which nodes are spreaders (right now, A+I is hardcoded as the two states people can be when they contact others). Finally, the total infected, we don't use anywhere, but it may be nice to encode that too (that'd be E, A, I and H, I suppose)

**Comment by bobturneruk** [comment]
This is substantial and excellent work. I suggest, and you were probably going to do this anyway, that the points @magicicada is happy with are split into separate issues (ideally referenced here) so that they can be worked on, and that further discussion takes place as time allows.

Couple of things from a skim over:
- Should the proposed `infect` function be `expose` (could be my lack of knowledge, here)?
- There are two heading 4s, could one become 5? I guess the discussion here is about "4. (optional) Parametrise S->E, spreader nodes and infected nodes"?

**Comment by aflag** [comment]
I didn't realise there were two 4s I will fix that. I will also create the issues, I just wanted to check if everyone was in the same page.

**Comment by aflag** [comment]
I've created the issues #262, #263 and #264. Still waiting for more input for the creation of the other 2.
