### ISSUE TITLE
Refactor and test Utilities module

### ISSUE THREAD

**Issue by peter-t-fox** [ScottishCovidResponse/SCRCIssueTracking#171]
The Utilities modules contains several functions which differ only in the type they operate on e.g.

```
double sum_calc(std::vector<double> v);
int sum_calc_int(std::vector<int> v);
```
These can trivially be replaced by generic template functions which act on any numeric type.

In addition, much of their functionality can be replaced by standard library routines such as `std::accumulate`.

Also, these functions can easily be unit tested, so this sould be a good starting point for writing some basic unit tests.

Update: Now that the majority of the functions have been removed, the only remaining code to test is the `sse_calc` function.

**Comment by thibaud-porphyre** [comment]
Some of the utilities function and functions in DistanceComputation.cpp are not used since they are legacy from the original model (animal-based). This might create discrepancies between functions. For example, sse_calc and sse_calc_int are different. Please use function that are used in the current model.
