### ISSUE TITLE
Create a virtual environment

### ISSUE THREAD

**Issue by bobturneruk** [ScottishCovidResponse/SCRCIssueTracking#202]
- Create a conda environment (`.yml` file) for this project
- Add instructions to `readme.md` on how to use it to create a virtual environment in which to run the code

**Comment by bobturneruk** [comment]
Might look a bit like:

```{yml}
name: simple_network_sim
channels:
  - conda-forge
dependencies:
  - python=3.7
  - networkx
  - matplotlib
```

Probably with more specific dependencies.

readme gets:
```{markdown}
1. [Install (Mini)Conda](https://docs.conda.io/en/latest/miniconda.html)
2. [Install git](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git)
3. Clone this repository using this command `git clone https://github.com/ScottishCovidResponse/simple_network_sim.git`
4. Import `simple_network_sim.yml` as a Conda environment `conda env create -f simple_network_sim`
5. Switch to this environment `conda activate simple_network_sim`
```

**Comment by aflag** [comment]
I made a PR for this. I've created a spec-file.txt (https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#building-identical-conda-environments), since that would give us a way to try and make builds more reproducible (although it ends up being system-dependent). Unfortunately, conda doesn't have something like Pipfile.lock (https://pipenv-fork.readthedocs.io/en/latest/basics.html#example-pipfile-pipfile-lock), so the spec-file.txt seemed the recommended way to have a reproducible environment.

If we have a Pipfile.lock + a base docker image, that would allow use to rebuild any commit and get the same results (provided pypi.org and docker.io are able to serve us the files we need). I think conda + spec-file.txt will get us close to Pipfile.lock + docker, but you will need linux to use the spec-file.txt.

Another thing that I find a bit annoying, which is solved with pipenv + setuptools, is that in conda there's no way to differentiate test requirements and run requirements, so everything will always be installed.

All in all I feel like Pipenv is great if we decide to use docker, but without docker, I think conda will give us better results.
