### ISSUE TITLE
Policy Input and behaviours

### ISSUE THREAD

**Issue by sam-brett** [ScottishCovidResponse/SCRCIssueTracking#259]
Apologies this is a bit of a brain dump, so please feel free to ask for clarification

From the discussion this morning, it appears we need to start thinking of a way of implementing different behaviour scenarios based on way points in the outbreak. These include but are not limited to:

* Regional/National Lockdowns - All non-essential travel stops, only medical, grocery and daily exercise. 
* "Stay Alert" - Relaxing above to allow some non-essential travel and more people working
* Schools/Work returning to normal

We also need to consider the behaviour of isolating individuals. If a person is alerted on day 20 that they came into contact with an infected person on day 12, should they isolate for 14 - (20-12) = 6 days, or should they isolate for 14 days going forward. 

### Stage 1
* create a new input file to contain policy data
* set a proportion of the population infected where lockdown is imposed
* set a proportion where the lockdown is relaxed
* Set a flag for whether isolation is relative (6 in above example) or absolute (14 in above example)
* set length of absolute isolation

### Stage 2
* update existing code to use these new features
* include todo's wherever input from Sibylle or Louise are required
* use best judgement but leave TODO's where unsure

**Comment by sibylleM** [comment]
Just to comment on the length of isolation: We thought this might be a good app configuration, asking people to only isolate the difference in days instead of a blanket "14 day" isolation, because nobody wants to constantly be alerted to self-isolate for 14 days. If we can show that using the app has the benefits of a shorter quarantine / self-isolation, that would be a good selling point for using the app. So if we could include a tailored length of self-isolation into the model (besides the 14 days to compare it to I guess), that would definitely be useful. Nevertheless, I'll discuss with Louise and we'll share the document on scenarios to explore with you. Also, many of the 'scenarios' could be driven by how the contacts looks like, i.e. we feed in contact networks where the contacts have labels for the nature of the contact (school, work, exercise,..) and dynamically turn these on and off depending on the scenario. Not sure if this made sense.. Of course all of this depends on whether you and Vino think this is something that can be added to the model and doesn't cause too much of a headache.

**Comment by vinopm** [comment]
@sibylleM @sam-brett Instead of turning on a lockdown policy when a set proportion of the population become infected, do you think it would be better to base this on R? For example when R > 1 then we have a strict lock down policy, and it is relaxed when R < 1?

**Comment by sibylleM** [comment]
Hi @vinopm , that's not a bad idea to base the lockdown on R. I just need to have a think if this fits with our scenarios right now or whether this is something to consider in a later version of the model. I've got a couple of meetings now but will get back on this.

**Comment by vinopm** [comment]
@sibylleM Thanks. I'll work on an initial implementation which will depend on the proportion of the population infected. Then we can replace this with R once you have considered if we need this now or could be considered in a later version as you suggested.
