### ISSUE TITLE
Speed up virus movement

### ISSUE THREAD

**Issue by claireh93** [ScottishCovidResponse/SCRCIssueTracking#426]
Had an idea to get rid of the multinomial call in `virusmove!`, because this will call many thousands of binomial draws in the loop, which is making things very slow. Instead we should have this step happen deterministically, and have deterministic force of infection stored in the cache, before randomising it to the `epi.abundances.matrix_v`

**Comment by wytbella** [comment]
can I ask a couple of questions?

> Instead we should have this step happen deterministically

Do you mean you want to make `calc_lookup_moves!` call deterministic and get rid of the sampling on Multinomial in it? So virus move becomes completely deterministic?

>and have deterministic force of infection stored in the cache

currently the force of infection seems to be stochastic rather than deterministic https://github.com/ScottishCovidResponse/Simulation.jl/blob/8764aa857ba5de372f3fa7a88936826f87c959c8/src/Epidemiology/EpiGenerate.jl#L59 It's drawn from a Poisson distribution. Which deterministic part do you want to store in the cache?

> before randomising it to the epi.abundances.matrix_v
do you want any stochastic element in `calc_lookup_moves!`/`virusmove!`?
