### ISSUE TITLE
Questions on sensitivity analysis / inference

### ISSUE THREAD

**Issue by bobturneruk** [ScottishCovidResponse/SCRCIssueTracking#460]
Which parameters do we want sensitivity analysis and eventually inference on?

1.	Compartment transition matrix
-	Do we want sensitivity to this parameter by age and by state? It’s equal for all age groups currently
-	How to bump one probability while keeping the sum == 1?
-	Do we want to have this parameter in common with other SCRC models, or infer?
-	How to choose priors for this?

	From my initial tests this is highly impactful

2.	Population
-	Parameter fixed per healthboard from census data, will this ever change/move, do we want to do inference on this?

3.	Movements
-	From  wu01uk, will this ever change/move, do we want to do inference on this?

4.	Mixing matrix
-	Do we want sensitivity to this parameter by age and by state?
-	If yes, it seems rather simple priors can be chosen for it (gaussian around current values?)

	From my tests this is quite impactful, but not sure what are correct test ranges. Mostly [17,70]->[17->70] is impactful.

5.	Movement/Contact multipliers
-	Will we infer or input this?

	Hugely impactful and allows appearance of multiple waves of disease. Only param that allows changing the time position of waves.

What sort of data do we have for inference (what granularity?) and do we need any other alternative datasets that I can help getting?
Do we want to make the model stochastic at some point?

**Comment by bobturneruk** [comment]
See https://github.com/ScottishCovidResponse/simple_network_sim/blob/master/doc/notebooks/Parameter%20sensitivity%20analysis.ipynb

**Comment by aflag** [comment]
> How to bump one probability while keeping the sum == 1?

Can you explain this a little better? Are you asking which edges to decrease when you make the rate of a certain transition higher? I suspect one of the obvious ones would be to just decrease the rate at which people remain in the given state.

**Comment by FiodorG** [comment]
Yes exactly, when you are in state A and can go to (A, B, C), if you increase A->B, which of A->A and A->C do you decrease?
- We can decrease A->A (but then what to do if we increase A->A?)
- We can decrease all other uniformly, this is what I've done

And this makes me think that setting a prior distribution on this matrix is quite tough (but maybe this problem has been solved already somewhere in the literature?)

**Comment by FiodorG** [comment]
After discussing with Rikiya, usually this is done through Dirichlet distributions (https://en.wikipedia.org/wiki/Dirichlet_distribution)

**Comment by FiodorG** [comment]
Answers from @magicicada :
I attempted to answer the inference-related questions as best I could
Which parameters do we want sensitivity analysis and eventually inference on?

Compartment transition matrix
- Do we want sensitivity to this parameter by age and by state?
- How to bump one probability while keeping the sum == 1?
- Do we want to have this parameter in common with other SCRC models, or infer?
- How to choose priors for this?
 From my initial tests this is highly impactful
A: We want to have these parameters in common with other SCRC models, and ideally the different ages should have different values – I think inference for these rates is happening elsewhere.

Population
- Parameter fixed per healthboard from census data, will this ever change/move, do we want to do inference on this?
A: I can’t imagine this changing much. If we get a newer or better version we might use it, but there’s no inference.

Movements
- From wu01uk, will this ever change/move, do we want to do inference on this?
A: The dataset doesn’t change, but we might want to use different slices of it (e.g. using only movements from a subset of industries.). Not likely to do inference on this.

Mixing matrix
- Do we want sensitivity to this parameter by age and by state?
- If yes, it seems rather simple priors can be chosen for it (gaussian around current values?)

 From my tests this is quite impactful, but not sure what are correct test ranges. Mostly [17,70]->[17->70] is impactful.

A: That will be the most impactful probably because it is by far the largest category of people. We are likely to use a version from data, or one agreed by the consortium, it may have different age categories.

Movement/Contact multipliers
- Will we infer or input this?
 Hugely impactful and allows appearance of multiple waves of disease. Only param that allows changing the time position of waves.
A: as discussed in our Monday meeting, we probably want to separate the transmission probability parameter and the movement/contact multipliers. The movement multiplier is at least somewhat form data – from Google Mobility Data. The contact multiplier we probably need to infer.

What sort of data do we have for inference (what granularity?) and do we need any other alternative datasets that I can help getting?
A: we have death data at the health board level, and (less reliable) detected case data at the health board level. I know the consortium has applied for data access to get death and case data at a finer geographic resolution.
