### ISSUE TITLE
PyCall shim for data_pipeline_api

### ISSUE THREAD

**Issue by richardreeve** [ScottishCovidResponse/SCRCIssueTracking#516]
While we work out the native julia API for the data / analysis pipeline, we need to have something working in the short term, and the obvious short term solution is to wrap the [python data_pipeline_api](https://github.com/ScottishCovidResponse/data_pipeline_api) code in a `PyCall` wrapper so that we can read from and write to the pipeline now. It's not ideal, but it doesn't seem like the native julia API will be ready in the next week, but this could be...

**Comment by AlexRobson** [comment]
I've taken a look at this and I can recreate the example script here: https://github.com/ScottishCovidResponse/data_pipeline_api/blob/master/examples/data_access.py

However, this seems limited to just the `read_table` API. To continue this, needs furhter investigation into how to make the equilvalent calls into the other API functions which i'm not sure right now how to construct.

Two other things to note: `read_table` is of course returning a Pandas.jl DataFrame rather than a julia DataFrame I don't know how the Distributions object will be dealt with (julia obviously has it's own native implementation...). The second is that this requires a bit of messing around with `PyCall`. The only way I could see it working with the conda environment was to build PyCall against that environment, so it may mess up any other uses of PyCall you may have. 

WIP: MR here: https://github.com/ScottishCovidResponse/SimulationData.jl/pull/1

**Comment by sdl1** [comment]
Yep `DataFrame(x)` should work. Not sure about the distribution objects but should be possible

**Comment by sdl1** [comment]
I can get Alex's PR working:
```julia
julia> DataFrame(read_table("human/mixing-matrix", "abc"))
[PYTHON]: Reading table
9×3 DataFrame
│ Row │ source  │ target  │ mixing    │
│     │ String  │ String  │ Float64   │
├─────┼─────────┼─────────┼───────────┤
│ 1   │ [0,17)  │ [0,17)  │ 2.15883   │
│ 2   │ [0,17)  │ [17,70) │ 1.64281   │
│ 3   │ [0,17)  │ 70+     │ 0.0953926 │
│ 4   │ [17,70) │ [0,17)  │ 0.540818  │
│ 5   │ [17,70) │ [17,70) │ 2.29122   │
│ 6   │ [17,70) │ 70+     │ 0.175799  │
│ 7   │ 70+     │ [0,17)  │ 0.0367362 │
│ 8   │ 70+     │ [17,70) │ 0.274034  │
│ 9   │ 70+     │ 70+     │ 0.0752173 │
```

So we probably just need to fix up the type conversions and then try to get it working within Simulation.jl 

One question is, do we want to support a proper session API right now? Currently it does
```python
    def read_table(data, component):
        print("[PYTHON]: Reading table")
        with SimpleNetworkSimAPI(
             $DEFAULT_CONFIG,
        ) as api:
            d = api.read_table(data)

        return d
```
i.e. each call has its own session. I imagine this is fine to start with?

**Comment by richardreeve** [comment]
I think they have to all use the same session, as the write out of the `.yaml` file that records all the reads and writes for upload to the data registry happens when the session closes. @mrow84 knows what's going on with this though, so is the best person to talk to - also about stuff beyond `read_table()`.

**Comment by mrow84** [comment]
Please refer to [this PR](https://github.com/ScottishCovidResponse/data_pipeline_api/pull/14) for the implementation of the "standard API".

**Comment by sdl1** [comment]
[This PR](https://github.com/ScottishCovidResponse/SimulationData.jl/pull/4) should hopefully implement most of the remaining stuff we want from the wrapper, at least on the read side.

**Comment by AlexRobson** [comment]
Now needs https://github.com/ScottishCovidResponse/SimulationData.jl/issues/5

**Comment by AlexRobson** [comment]
Should be addressed by https://github.com/ScottishCovidResponse/SimulationData.jl/pull/8

Think that it also needs https://github.com/ScottishCovidResponse/data_pipeline_api/pull/26 to switch away from the custom branch.

**Comment by sdl1** [comment]
Adding write methods to the julia API wrapper: https://github.com/ScottishCovidResponse/SimulationData.jl/pull/12

**Comment by claireh93** [comment]
Closed with ScottishCovidResponse/Simulation.jl#67
