### ISSUE TITLE
Eliminate clang-analyzer warnings

### ISSUE THREAD

**Issue by ianhinder** [ScottishCovidResponse/SCRCIssueTracking#594]
After enabling clang-analyzer, we have 9 warnings from it. See, e.g. https://github.com/ScottishCovidResponse/CoronaPMCMC/actions/runs/163654302.  One of these looks like it might be serious:
```
model.cc:901#L10
warning: The left operand of '==' is a garbage value
```

**Comment by rwj11** [comment]
> warning: Declared variable-length array (VLA) has zero size

VLAs aren't part of any C++ standard, and are unlikely to become one.  Even in C, they have been an optional (rather than standard) feature as of the 2011 standard, and aren't supported by the current MSVC compiler.  The detail is discussed here: https://stackoverflow.com/questions/1887097/why-arent-variable-length-arrays-part-of-the-c-standard

**Comment by rwj11** [comment]
> model.cc:901#L10
> warning: The left operand of '==' is a garbage value

I can't see how control flow gets here without `k` being initialised.
The warning goes away if `k` is initialised at creation, or also if the loop is convert from `while() {}` to `do { } while();`: the test on `cst.size()` when the loop initialises is I think redundant, as this has just been the subject of `if(cst.size() == 0) break;`, and `.size()` is unsigned.

**Comment by ianhinder** [comment]
See [PR](https://github.com/ScottishCovidResponse/BEEPmbp/pull/12).

**Comment by ianhinder** [comment]
PR merged.
